// Fixed list of trades ("Gewerke"), based on https://www.clean-invoice.com/gewerke,
// using gender-neutral forms (e.g. "Schreinerei" instead of "Schreiner").
export const TRADES: string[] = [
  'Anlagenmechanik',
  'Bauleitung & Projektmanagement',
  'Bauwerksabdichtung',
  'Bodenbeschichtung',
  'Bodenverlegung',
  'Brandschutz',
  'Dachdeckerei',
  'Elektroprüfung (DGUV V3)',
  'Elektrotechnik',
  'Entrümpelung & Haushaltsauflösung',
  'Estrichbau',
  'Feinwerkmechanik',
  'Fensterbau',
  'Fliesenverlegung',
  'Galvanik',
  'Garten- & Landschaftsbau',
  'Gebäudereinigung',
  'Glaserei',
  'Hausmeisterservice',
  'Heizung & Sanitär',
  'Kälte- & Klimatechnik',
  'Kfz-Technik',
  'Klempnerei',
  'Küchenmontage',
  'Land- & Baumaschinentechnik',
  'Malerei',
  'Maurerei & Betonbau',
  'Metallbau',
  'Möbelmontage & Innenausbau',
  'Photovoltaik',
  'Polsterei & Raumausstattung',
  'Schreinerei / Tischlerei',
  'Sicherheitstechnik',
  'Stuckatur & Putz',
  'Trockenbau',
  'Umzugs- & Transportservice',
  'Werbetechnik & Beschriftung',
  'Zaun- & Tortechnik',
  'Zimmerei',
];
